NUMPY
support of arrays and matrices, mathematical functions

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(type(arr1))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.reshape(1,5)
print(arr2)
arr2.reshape(1, -1)  # -1 allows numpy to infer the size of that dimension
print(arr2)
print(arr2.shape)
print(type(arr2))

[[1 2 3 4 5]]
[[1 2 3 4 5]]
(1, 5)
<class 'numpy.ndarray'>


In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


In [10]:
np.arange(0,10,2)  # Generates an array with values from 0 to 10 with a step of 2


array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,10,2).reshape(5,1) 

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4)) # Creates a 3x4 array filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
##identity matrix
np.eye(3)  # Creates a 3x3 identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr = np.array([[1,2,3], [4,5,6]])
print("Array:\n", arr)
print("Shape of the array:", arr.shape)
print("Type of the array:", type(arr))
print("Number of dimensions:", arr.ndim)
print("Size of the array:", arr.size)
print("Data type of the array:", arr.dtype)
print("Item size in bytes:", arr.itemsize)#output:varys based on platform

Array:
 [[1 2 3]
 [4 5 6]]
Shape of the array: (2, 3)
Type of the array: <class 'numpy.ndarray'>
Number of dimensions: 2
Size of the array: 6
Data type of the array: int32
Item size in bytes: 4


In [16]:
### Numpy Vectorized operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
 # Element-wise 
print("Sum of arrays:", arr1 + arr2)
print("Product of arrays:", arr1 * arr2)
print("Difference of arrays:", arr1 - arr2)
print("Quotient of arrays:", arr1 / arr2)

Sum of arrays: [11 22 33 44 55]
Product of arrays: [ 10  40  90 160 250]
Difference of arrays: [ -9 -18 -27 -36 -45]
Quotient of arrays: [0.1 0.1 0.1 0.1 0.1]


In [17]:
#universal functions
print("Square root of arr1:", np.sqrt(arr1))
print("Exponential of arr1:", np.exp(arr1))
print("Sine of arr1:", np.sin(arr1))
print("Logarithm of arr2:", np.log(arr2))

Square root of arr1: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of arr1: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine of arr1: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Logarithm of arr2: [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [21]:
## array slicing and indexing
arr = np.array([[1, 2, 3, 10], [4, 5, 6, 20], [7, 8, 9, 30]])
print("Original Array:\n", arr)
print("First row:", arr[0])
print("First column:", arr[:, 0])
print("Last column:", arr[:, -1])
print("Element at (1, 2):", arr[1, 2])
print("Sub-array (first two rows, first three columns):\n", arr[:2, :3])
print("accessing 6 20 9 30: \n",arr[1:,2:])
print("Elements greater than 5:\n", arr[arr > 5])


Original Array:
 [[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]
First row: [ 1  2  3 10]
First column: [1 4 7]
Last column: [10 20 30]
Element at (1, 2): 6
Sub-array (first two rows, first three columns):
 [[1 2 3]
 [4 5 6]]
accessing 6 20 9 30: 
 [[ 6 20]
 [ 9 30]]
Elements greater than 5:
 [10  6 20  7  8  9 30]


In [25]:
print(arr[0][0])
print(arr[0:2])
print(arr[0:2, 2:])
print(arr[1:,1:3])

1
[[ 1  2  3 10]
 [ 4  5  6 20]]
[[ 3 10]
 [ 6 20]]
[[5 6]
 [8 9]]


In [27]:
arr[0][0] = 100  # Modifying an element
print("Modified Array:\n", arr)
arr[1:] = 100
print(arr)

Modified Array:
 [[100   2   3  10]
 [  4   5   6  20]
 [  7   8   9  30]]
[[100   2   3  10]
 [100 100 100 100]
 [100 100 100 100]]


In [28]:
### statistics -- Normalization
#to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])
#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
#normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)
#Output:

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Original Array:", arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Median:", np.median(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Sum:", np.sum(arr))

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Median: 5.5
Minimum: 1
Maximum: 10
Sum: 55


In [31]:
#Logical operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ])
data[data>5 ]
data[(data>5) & (data < 9)] 

array([6, 7, 8])

In [6]:
x = np.array([[1,2,3]])
print(x.shape)
print(type(x))
print(x.ndim)

(1, 3)
<class 'numpy.ndarray'>
2


In [10]:
y = np.full((2,2),5)


In [11]:
y

array([[5, 5],
       [5, 5]])

In [13]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
idx = (a > 2)  # Create a boolean index array
print("Boolean Index Array:\n", idx)
print(a[idx])  # Use the boolean index to filter the array
print(a[a > 2])  # Another way to filter using boolean indexing

[[1 2 3]
 [4 5 6]]
Boolean Index Array:
 [[False False  True]
 [ True  True  True]]
[3 4 5 6]
[3 4 5 6]
